### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sreuter** [yairEO/relative-time#3]
Awesome convenience package. Any plans for adding types?

**Comment by yairEO** [comment]
Thanks! 

I don't know/like typescript at all. and don't see the benefit in it. been coding in JS for almost 20 years without it, and had no issues, and seen things come and go and hopefully typescript will also go :)

**Comment by bengry** [comment]
I've created https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56104 to address this.

@yairEO if you prefer, I can send a PR to this repo so that the types would be built-in (i.e. users won't have to both `npm install @yaireo/relative-time` AND `npm install -D @types/yaireo__relative-time`, but rather just get everything from doing the first one. (and then close https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56104 since it would be redundant).

**Comment by yairEO** [comment]
@bengry - and who will maintain this? (I don't foresee any changes but still)

**Comment by bengry** [comment]
> @bengry - and who will maintain this? (I don't foresee any changes but still) 

The types need maintenance anyway, unless the library is written in TypeScript of course (which from my understanding of your previous comment, you don't want to migrate to). So it doesn't _really_ matter, besides being up proactive vs. reactive to API changes.
In either case you'll need someone to write the code to adapt, so if it's here or in the DefinitelyTyped repo, it's the same thing at the end of the day.

**Comment by yairEO** [comment]
Yeah, I know :) in other words, you are adding me more work :) 

why does typescript even matter here?
the API is simple and any person who is using my lib will read how to use in the README and then go implement it, it's 2 lines of code.. I really don't see what benefit typescript, it's just complicating things, adding more files which needs to be maintained

I cannot possibly tell you how much I dislike *typescript*, just like I disliked *coffeescript* a few years ago in 2013 and it also died. just a bunch of uselessness that people that are coming from other languages invented to complicate things. For ~20 years I have had no problem writing JS without it

I have dozens of open-source projects and sometimes people ask for `typescript` support, so I just tell them - if you want it, go write it in **DefinitelyTyped** and you are in charge of maintaining it, since you wanted it :) 

If your kids wants a dog, they better know they must take it for a walk themselves ;)

**Comment by bengry** [comment]
I'm not adding more work, I side-stepped it by publishing them on DefinitelyTyped, making the two decoupled. There are no promises that if you publish a breaking change tomorrow, the types package would work, and there's no expectancy that it will (unless of course that types package is updated too to support it).

I agree with you in essence, but:
1. With TypeScript being so prevalent, [some] people have come to expect all packages to just be typed, and if their IDE has automatic type acquisition turned on, they get it "for free" today for a lot of packages, and now for this one too. I'm sure you're also benefiting from this, even when working with JS in VS Code (or whatever other modern IDE I assume you're using daily). The intellisense it provides is powered by TypeScript and its ecosystem, even if you don't officially opt-into it.
2. For TS to not error on you for using a non-typed module, you have to add a line in your codebase that basically says that this is fine. (`declare module 'foo'`, to be specific). Having types, even ones that are very short - saves that from devs using the package, some of them don't even know that this needs to be done.
3. Like you said yourself, this is a very simple package. It's a nice utility, but you could just write it yourself in your codebase (you being the potential user of this relative time package). So just like you can type it yourself inside your project, you can write the whole package yourself too and it wouldn't be complex or even long. Yet there's still value it having it packaged-up, and be ready to be re-used in different projects as needed/wanted.

**Comment by yairEO** [comment]
Yeah I am aware of all this already

**Comment by DaniGuardiola** [comment]
@yairEO I was ready to thank you for this library, but your attitude here is terrible. It's fine to not like/use a technology, but you've been pretty disrespectful and condescending throughout this thread. I hope someone forks this and adds native typescript support. Or not, it doesn't really matter, but at least I hope it's someone with a more constructive attitude.

**Comment by yairEO** [comment]
How do you expect such support to be addressed in the code? 
An extra file specifically for *TS* aficionados? 

Do does NPM knows which file to serve? How do I keep supporting all those users who don't
use TS and still want to use this lib? I don't know the answer to all these questions.. I don't even know TS :)

**Comment by DaniGuardiola** [comment]
@bengry was literally offering to take care of that for you. https://github.com/yairEO/relative-time/issues/3#issuecomment-932165488

**Comment by yairEO** [comment]
@DaniGuardiola - OK, if @bengry still want to.

But still, non-typescript packages may be used in a typescript codebase without a problem with some minor 2-minutes configuration that will not print any IDE warnings

**Comment by DaniGuardiola** [comment]
@yairEO that isn't typescript support, that is just making typescript not fail by removing all type-safety, which is the point of TS in the first place.

**Comment by yairEO** [comment]
@DaniGuardiola OK, you got me :)

If a volunteer does this, please use the [`Intl.RelativeTimeFormat` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat) as the reference *typescript* types

I don't know Typescript and am swamped with work.. I've once tried to learn it and it took days and I ended up not understanding anything

**Comment by bengry** [comment]
I don't mind doing the migration. All it takes is to basically copy over [the types from DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yaireo__relative-time/index.d.ts) into this repo, and add a `types` entry in the `package.json` pointing to the `d.ts` file.
After a new version that includes the types is published it's worth [removing the types from DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package).

Having said that, I don't have the time to do this right now (mainly to test this), so if anyone wants to take this - feel free to do so.

@yairEO the types [already use](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7347cc9d8a85528925203cc472075f98f59acdc5/types/yaireo__relative-time/index.d.ts#L16) that API itself.

**Comment by yairEO** [comment]
Thanks @bengry - just released a new version with what you said
